version: '3'

services:
  nginx:
    build: ./nginx
    links:
      - lightbar-a
      - lightbar-b
      - lightbar-c
      - lightbar-d
    ports:
     - "80:80"
    networks:
      - lightbar

  lightbar-a:
    build: ./app
    links:
      - redis
    expose:
      - "5000"
    environment:
      - FLASK_SECRET_KEY
    networks:
      - lightbar

  lightbar-b:
    build: ./app
    links:
      - redis
    expose:
      - "5000"
    environment:
      - FLASK_SECRET_KEY
    networks:
      - lightbar

  lightbar-c:
    build: ./app
    links:
      - redis
    expose:
      - "5000"
    environment:
      - FLASK_SECRET_KEY
    networks:
      - lightbar

  lightbar-d:
    build: ./app
    links:
      - redis
    expose:
      - "5000"
    environment:
      - FLASK_SECRET_KEY
    networks:
      - lightbar

  redis:
    image: redis:alpine
    expose:
      - "6379"
    networks:
      - lightbar

networks:
  lightbar:
