version: '3'

services:
  nginx:
    build: ./nginx
    links:
      - lightbar
    ports:
     - "80:80"
    networks:
      - lightbar

  lightbar:
    build: 
      context: .
      dockerfile: ./app/Dockerfile
    links:
      - redis
    expose:
      - "5000"
    environment:
      - FLASK_SECRET_KEY
    networks:
      - lightbar
    volumes: 
      - ./app:/

  redis:
    image: redis:alpine
    expose:
      - "6379"
    networks:
      - lightbar

networks:
  lightbar:
